# Set working directory
workdir: "/workspace/results"

# Prefix of all output files
sample_name: ""  # Dynamically passed via --config

# Reference genome
genome: ""  # Dynamically passed via --config

# Input FASTQ file
fastq: ""  # Dynamically passed via --config

# Aligner to use (minimap2 or ngmlr; default: minimap2)
aligner: "minimap2"

# Options passed to minimap2 (optional)
minimap2_opts: ""

use_region: true  # or false

# Region of interest
region: ""  # Dynamically passed via --config

# Options passed to sniffles
sniffles_opts: "--minsvlen 50 --tandem-repeats"

# Tandem repeat BED file
tandem_repeat_region: ""  # Dynamically passed via --config

# Threads and other configurations
threads: 100
num_shards: 30
deepvariant_bin_version: "1.5.0"
