name: laseR_DNA_DV
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nanostat=1.6
  - snakemake=7.18.2
  - python>3.6
  - minimap2=2.26
  - ngmlr=0.2.7
  - samtools=1.09
  - longshot=0.4.1
  - seqkit=2.9.0